export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const PREV_ROUTE = 'PREV_ROUTE';
export const NEXT_ROUTE = 'NEXT_ROUTE';

export const SELECT_SUBMISSION_TYPE = 'SELECT_SUBMISSION_TYPE';
export const SELECT_SUBMISSION_AGENCY = 'SELECT_SUBMISSION_AGENCY';
export const UPDATE_SUBMISSION_MESSAGE = 'UPDATE_SUBMISSION_MESSAGE';
export const START_SUBMIT_SUBMISSION = 'START_SUBMIT_SUBMISSION';
export const RECEIVE_SUBMIT_SUBMISSION = 'RECEIVE_SUBMIT_SUBMISSION';
export const RESET_SUBMISSION = 'RESET_SUBMISSION';

export const REQUEST_AGENCIES = 'REQUEST_AGENCIES';
export const RECEIVE_AGENCIES = 'RECEIVE_AGENCIES';
export const RESET_AGENCIES = 'RESET_AGENCIES';
export const SEARCH_AGENCIES = 'SEARCH_AGENCIES';

export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const RESET_USER = 'RESET_USER';

export const ADD_ALERT = 'ADD_ALERT';
export const DISMISS_ALERT = 'DISMISS_ALERT';
export const DISMISS_ALL_ALERTS = 'DISMISS_ALL_ALERTS';
