export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';
export const PREV_ROUTE = 'PREV_ROUTE';
export const NEXT_ROUTE = 'NEXT_ROUTE';

export const SELECT_SUBMISSION = 'SELECT_SUBMISSION';
export const SELECT_AGENCY = 'SELECT_AGENCY';

export const REQUEST_AGENCIES = 'REQUEST_AGENCIES';
export const RECEIVE_AGENCIES = 'RECEIVE_AGENCIES';
export const RESET_AGENCIES = 'RESET_AGENCIES';
